=== MateoCarballo/LenguajeDeMarcas/Evaluacion_01/Ejercicios/XSD/Carpeta Personal/Entregable/Alquiler.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- DEFINICIONES DE ELEMENTOS -->
  
<!-- Definicion de alquiler -->
<xs:element name="gestionAlquiler">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="sucursal" maxOccurs="unbounded" />
      <xs:element ref="clientes" />
    </xs:sequence>
    <xs:attribute name="cif" type="tipoCif"/>
    <xs:attribute name="nombre" type="xs:string"/>
  </xs:complexType>
</xs:element>
  
<!--Definicion de sucursal -->
  <xs:element name="sucursal">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="vehiculo" maxOccurs="unbounded"/>
      </xs:sequence>
       <xs:attribute name="cantidadTotalvehiculos" type="xs:integer"/>
      <xs:attribute name="direccion" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
          <!--Definicion de vehiculo-->
          <xs:element name="vehiculo">
            <xs:complexType>
              <xs:sequence>
                <xs:element ref="estado"/>
                <xs:element name="tipoDevehiculo" type="tipoVehiculo"/>
                <xs:element name="marca" type="xs:string"/>
                <xs:element name="modelo" type="xs:string"/>
                <xs:element name="fechaMatriculacion" type="tipoFecha"/>
                <xs:element name="kilometraje" type="xs:integer"/>
                <xs:element name="matricula" type="tipoMatriculaES"/>
                <xs:element ref="potencia"/>
                <xs:element name="peso" type="xs:integer"/>
                <xs:element ref="precioDia"/>
                <xs:element name="descripcion" type="xs:string"/>
              </xs:sequence>
              <xs:attribute name="idVehiculo" type="tipoIdvehiculo"/>
            </xs:complexType>
            
          </xs:element>
          
          <!--Definicion de estado-->
          <xs:element name="estado">
          <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="ocupado" type="tipoBooleanoSiNo"/>
                </xs:extension>
              </xs:simpleContent>
            </xs:complexType>
          </xs:element>
          
          <!--Definicion de potencia-->
          <xs:element name="potencia">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:unsignedByte">
                <xs:attribute name="unidades" type="xs:string"/>
              </xs:extension>
            </xs:simpleContent>
            </xs:complexType>
          </xs:element>
          
          <!--Definicion de precioDia-->
          <xs:element name="precioDia">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:unsignedByte">
                <xs:attribute name="moneda" type="xs:string"/>
              </xs:extension>
            </xs:simpleContent>
            </xs:complexType>
          </xs:element>
  
  <!--Definicion de clientes -->
  <xs:element name="clientes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cliente"/>
      </xs:sequence>
      <xs:attribute name="cantidadTotalClientes" type="xs:integer"/>
    </xs:complexType>
    
  </xs:element>
  
            <!--Definicion de cliente -->
            <xs:element name="cliente">
              <xs:complexType>
                <xs:sequence>
                  <xs:group ref="grupoElementosCliente"/>
                  <xs:element ref="alquileresActivos"/>
                  <xs:element ref="alquileresTerminados"/>
                </xs:sequence>
                <xs:attribute name="idCliente" type="tipoIdCliente"/>
              </xs:complexType>
              
            </xs:element>
  
          <xs:group name="grupoElementosCliente">
            <xs:sequence>
              <xs:element name="nombre" type="tipoNombre"/>
              <xs:element name="apellido1" type="tipoNombre"/>
              <xs:element name="apellido2" type="tipoNombre"/>
              <xs:element name="fechaNacimiento" type="tipoFecha"/>
              <xs:element name="telefonoContacto" type="tipoTelefono"/>
              <xs:element name="correo" type="tipoCorreo"/>
            </xs:sequence>
          </xs:group>


          <xs:element name="alquileresActivos">
            <xs:complexType>
              <xs:sequence>
              <xs:element name="alquiler" type="tipoAlquiler" maxOccurs="unbounded"/>
            </xs:sequence>
            </xs:complexType>
          </xs:element>
          
          <xs:element name="alquileresTerminados">
            <xs:complexType>
              <xs:sequence>
              <xs:element name="alquiler" type="tipoAlquiler" maxOccurs="unbounded"/>
            </xs:sequence>
            </xs:complexType>
          </xs:element>
<!--DEFINICIONES DE TIPOS CON Y SIN RESTRICCIONES-->
  <!-- Restricciones para el CIF
Debe tener:
1 Letra al principio
7 Digitos
1Letra al final
El algoritmo es mas complejo y se puede comprobar su validez pero por ahora nos vale esto  
   -->
  <xs:simpleType name="tipoCif">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{1}[0-9]{7}[A-Z]{1}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Definicion tipoIdCliente-->
  <xs:simpleType name="tipoIdCliente">
    <xs:restriction base="xs:string">
      <xs:pattern value="CL[0-9]{4}"/>
    </xs:restriction>
  </xs:simpleType>

<!--Definicion tipoIdvehiculo-->
  <xs:simpleType name="tipoIdvehiculo">
    <xs:restriction base="xs:string">
      <xs:pattern value="FU[0-9]{4}|CO[0-9]{4}|CA[0-9]{4}|MO[0-9]{4}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Definicion tipoNombre-->
  <xs:simpleType name="tipoNombre">
    <xs:restriction base="xs:string">
      <xs:pattern value=" [A-Z]{1}[a-z]{1,20}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!-- Definicion tipoBooleanoSiNo-->
  <xs:simpleType name="tipoBooleanoSiNo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="S"/>
      <xs:enumeration value="s"/>
      <xs:enumeration value="N"/>
      <xs:enumeration value="n"/>
      <xs:enumeration value="Si"/>
      <xs:enumeration value="si"/>
      <xs:enumeration value="No"/>
      <xs:enumeration value="no"/>
    </xs:restriction>
  </xs:simpleType>
  
   <!-- Definicion tipoVehiculo-->
  <xs:simpleType name="tipoVehiculo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Coche"/>
      <xs:enumeration value="Moto"/>
      <xs:enumeration value="Furgoneta"/>
      <xs:enumeration value="Caravana"/>
    </xs:restriction>
  </xs:simpleType>
  
   <!--Definicion de tipo fecha-->
            <xs:simpleType name="tipoFecha">
              <xs:restriction base="xs:string">
                <xs:pattern value="20[0-9]{2}/(0[1-9]|1[0-2])/(0[1-9]|[12][0-9]|3[01])"/>
              </xs:restriction>
            </xs:simpleType>
            
<!--Definicion de tipo fecha-->
<xs:simpleType name="tipoMatriculaES">
  <xs:restriction base="xs:string">
    <xs:pattern value="[0-9]{4}[A-Z]{3}"/>
  </xs:restriction>
</xs:simpleType>

<!--Definicion de tipo telefono-->
<xs:simpleType name="tipoTelefono">
  <xs:restriction base="xs:string">
    <xs:pattern value="[1-9]{1}[0-9]{8}"/>
  </xs:restriction>
</xs:simpleType>

<!--Definicion de tipo correo-->
<xs:simpleType name="tipoCorreo">
  <xs:restriction base="xs:string">
    <xs:pattern value="[a-z]{1,25}@[a-z]{5,9}.(es|com)"/>
  </xs:restriction>
</xs:simpleType>

<!--Definicion de tipo alquiler-->
<xs:complexType name="tipoAlquiler">
  <xs:sequence>
    <xs:element name="inicio" type="tipoFecha"/>
    <xs:element name="fin" type="tipoFecha"/>
  </xs:sequence>
  <xs:attribute name="vehiculoAlquilado" type="tipoIdvehiculo"/>
</xs:complexType>
</xs:schema>

=== MateoCarballo/LenguajeDeMarcas/Ejercicios/XSD/Carpeta Personal/Entregable/Alquiler.xml
<?xml version="1.0" encoding="UTF-8"?>
<alquiler xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xsi:noNamespaceSchemaLocation="Alquiler.xsd"
              cif="A12345678" nombre="nombre compania">

  <sucursal cantidadTotalvehiculos="345" direccion="C/ sucursal 1, numero 1">
    <vehiculo idvehiculo="Co1000">
      <estado ocupado="No"/>
      <tipo>Coche</tipo>
      <marca>marcaDeCoche</marca>
      <modelo>modeloDeCoche</modelo>
      <fechamatriculacion>2023/11/07</fechamatriculacion>
      <kilometraje>210000</kilometraje>
      <matricula>1234ABC</matricula>
      <potencia unidades="cv">100</potencia>
      <peso>1450</peso>
      <precioDia moneda="euros">100</precioDia>
      <descripcion>Este modelo en concreto viene equipado con la tecnologia S&amp;S (Start and Stop) 
      que apaga el motor cuando nos detenemos para ahorar combustible y evitar contaminar innecesariamente</descripcion>
    </vehiculo>
    
    <vehiculo idvehiculo="Fu1000">
      <estado ocupado="No"/>
      <tipo>Furgoneta</tipo>
      <marca>marcaDeFurgoneta</marca>
      <modelo>modeloDeFurgoneta</modelo>
      <fechamatriculacion ano="2018" mes="Febrero" dia="10"/>
      <kilometraje>167548</kilometraje>
      <matricula>2346JGF</matricula>
      <potencia unidades="cv">150</potencia>
      <peso unidades="kg">1750</peso>
      <precioDia moneda="euros">100</precioDia>
      <descripcion>Breve descripcion del vehiculo</descripcion>
    </vehiculo>
    
    <vehiculo idvehiculo="Ca1000">
      <estado ocupado="No"/>
      <tipo>Caravana</tipo>
      <marca>marcaDeCaravana</marca>
      <modelo>modeloDeCaravana</modelo>
      <fechamatriculacion ano="2019" mes="Enero" dia="1"/>
      <kilometraje>50000</kilometraje>
      <matricula>9012GHI</matricula>
      <potencia unidades="cv">200</potencia>
      <peso>3500</peso>
      <precioDia moneda="euros">100</precioDia>
      <descripcion>Breve descripcion del vehiculo</descripcion>
    </vehiculo>
  </sucursal>

  <sucursal cantidadTotalvehiculos="345" direccion="C/ sucursal 2 , numero 2">
  
    <vehiculo idvehiculo="Co2000">
      <estado ocupado="No"/>
      <tipo>Coche</tipo>
      <marca>marcaDeCoche</marca>
      <modelo>modeloDeCoche</modelo>
      <fechamatriculacion ano="2023" mes="Enero" dia="1"/>
      <kilometraje>210000</kilometraje>
      <matricula>1234ABC</matricula>
      <potencia unidades="cv">100</potencia>
      <peso>1450</peso>
      <precioDia moneda="euros">100</precioDia>
      <descripcion>Este modelo en concreto viene equipado con la tecnologia S&amp;S (Start and Stop) 
      que apaga el motor cuando nos detenemos para ahorar combustible y evitar contaminar innecesariamente</descripcion>
    </vehiculo>
    
    <vehiculo idvehiculo="Fu2000">
      <estado ocupado="No"/>
      <tipo>Furgoneta</tipo>
      <marca>marcaDeFurgoneta</marca>
      <modelo>modeloDeFurgoneta</modelo>
      <fechamatriculacion ano="2023" mes="Febrero" dia="10"/>
      <kilometraje>167548</kilometraje>
      <matricula>2346JGF</matricula>
      <potencia unidades="cv">150</potencia>
      <peso>1750</peso>
      <precioDia moneda="euros">100</precioDia>
      <descripcion>Breve descripcion del vehiculo</descripcion>
    </vehiculo>
    
    <vehiculo idvehiculo="Ca2000">
    <estado ocupado="Si"/>
      <tipo>Caravana</tipo>
      <marca>marcaDeCaravana</marca>
      <modelo>modeloDeCaravana</modelo>
      <fechamatriculacion ano="2023" mes="Enero" dia="1"/>
      <kilometraje>50000</kilometraje>
      <matricula>9012GHI</matricula>
      <potencia unidades="cv">200</potencia>
      <peso>3500</peso>
      <precioDia moneda="euros">100</precioDia>
      <descripcion>Breve descripcion del vehiculo</descripcion>
    </vehiculo>
  </sucursal>

  <clientes cantidadTotalclientes="543">
    <cliente idcliente="CL1001">
      <nombre>nombreclientesuno</nombre>
      <apellido1>Apellidouno</apellido1>
      <apellido2>Apellidodos</apellido2>
      <fechaNacimiento>1990/04/21</fechaNacimiento>
      <telefonoContacto>111111111</telefonoContacto>
      <correo>correo@clientes1.com</correo>
      <Activo>
        <Alquiler idvehiculo="Ca2000">
          <Inicio>2023/11/1</Inicio>
          <Fin>2023/11/1</Fin>
        </Alquiler>
      </Activo>
    </cliente>
    
    <cliente idcliente="CL2002">
      <nombre>nombreclientesuno</nombre>
      <apellido1>Apellidouno</apellido1>
      <apellido2>Apellidodos</apellido2>
      <telefonoContacto>222222222</telefonoContacto>
      <correo>correo@clientes2.com</correo>
      <fechaNacimiento>2023/11/1</fechaNacimiento>
    </cliente>
  </clientes>

</alquiler>

=== MateoCarballo/LenguajeDeMarcas/Evaluacion_01/Ejercicios/XSD/Carpeta Personal/Entregable/Alquiler.xml
<?xml version="1.0" encoding="UTF-8"?>
<gestionAlquiler xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                            xsi:noNamespaceSchemaLocation="Alquiler.xsd"
                            cif="A1234567Z"
                            nombre="nombre compania">

  <sucursal cantidadTotalvehiculos="345" direccion="C/  1, numero 1">
<vehiculo idVehiculo="CO1000">
      <estado ocupado="No"/>
      <tipoDevehiculo>Coche</tipoDevehiculo>
      <marca>marcaDeCoche</marca>
      <modelo>modeloDeCoche</modelo>
      <fechaMatriculacion>2023/08/01</fechaMatriculacion>
      <kilometraje>210000</kilometraje>
      <matricula>1234ABC</matricula>
      <potencia unidades="cv">100</potencia>
      <peso>1450</peso>
      <precioDia moneda="euros">100</precioDia>
      <descripcion>S&amp;S (Start and Stop) </descripcion>
    </vehiculo>
    
  <vehiculo idVehiculo="FU1000">
      <estado ocupado="No"/>
      <tipoDevehiculo>Furgoneta</tipoDevehiculo>
      <marca>marcaDeFurgoneta</marca>
      <modelo>modeloDeFurgoneta</modelo>
      <fechaMatriculacion>2023/11/20</fechaMatriculacion>
      <kilometraje>167548</kilometraje>
      <matricula>2346JGF</matricula>
      <potencia unidades="cv">150</potencia>
      <peso>1750</peso>
      <precioDia moneda="euros">100</precioDia>
      <descripcion>Breve descripcion del vehiculo</descripcion>
    </vehiculo>
    
  <vehiculo idVehiculo="CA1000">
      <estado ocupado="No"/>
      <tipoDevehiculo>Caravana</tipoDevehiculo>
      <marca>marcaDeCaravana</marca>
      <modelo>modeloDeCaravana</modelo>
      <fechaMatriculacion>2023/11/20</fechaMatriculacion>
      <kilometraje>50000</kilometraje>
      <matricula>9012GHI</matricula>
      <potencia unidades="cv">200</potencia>
      <peso>3500</peso>
      <precioDia moneda="euros">100</precioDia>
      <descripcion>Breve descripcion del vehiculo</descripcion>
    </vehiculo>
  </sucursal>
  
  <sucursal cantidadTotalvehiculos="346" direccion="C/  2 , numero 2">
    <vehiculo idVehiculo="CO2000">
      <estado ocupado="No"/>
      <tipoDevehiculo>Coche</tipoDevehiculo>
      <marca>marcaDeCoche</marca>
      <modelo>modeloDeCoche</modelo>
      <fechaMatriculacion>2023/11/07</fechaMatriculacion>
      <kilometraje>210000</kilometraje>
      <matricula>1234ABC</matricula>
      <potencia unidades="cv">100</potencia>
      <peso>1450</peso>
      <precioDia moneda="euros">100</precioDia>
      <descripcion>Este modelo en concreto viene equipado con la tecnologia S&amp;S (Start and Stop) 
      que apaga el motor cuando nos detenemos para ahorar combustible y evitar contaminar innecesariamente</descripcion>
    </vehiculo>
    
    <vehiculo idVehiculo="FU2000">
      <estado ocupado="No"/>
      <tipoDevehiculo>Furgoneta</tipoDevehiculo>
      <marca>marcaDeFurgoneta</marca>
      <modelo>modeloDeFurgoneta</modelo>
      <fechaMatriculacion>2021/01/04</fechaMatriculacion>
      <kilometraje>167548</kilometraje>
      <matricula>2346JGF</matricula>
      <potencia unidades="cv">150</potencia>
      <peso>1750</peso>
      <precioDia moneda="euros">100</precioDia>
      <descripcion>Breve descripcion del vehiculo</descripcion>
    </vehiculo>
    
    <vehiculo idVehiculo="CA2000">
    <estado ocupado="Si"/>
      <tipoDevehiculo>Caravana</tipoDevehiculo>
      <marca>marcaDeCaravana</marca>
      <modelo>modeloDeCaravana</modelo>
      <fechaMatriculacion>2001/06/21</fechaMatriculacion>
      <kilometraje>50000</kilometraje>
      <matricula>9012GHI</matricula>
      <potencia unidades="cv">200</potencia>
      <peso>3500</peso>
      <precioDia moneda="euros">100</precioDia>
      <descripcion>Breve descripcion del vehiculo</descripcion>
    </vehiculo>
  </sucursal>

  <clientes cantidadTotalClientes="543">
    <cliente idCliente="CL1001">
      <nombre>Nombreclientesuno</nombre>
      <apellido1>Apellidouno</apellido1>
      <apellido2>Apellidodos</apellido2>
      <fechaNacimiento>1990/04/21</fechaNacimiento>
      <telefonoContacto>111111111</telefonoContacto>
      <correo>correo@clientes1.com</correo>
      <alquilerActivos>
        <alquiler idvehiculo="Ca2000">
          <inicio>2023/11/1</inicio>
          <fin>2023/11/1</fin>
        </alquiler>
      </alquilerActivos>
    </cliente>
    
    <cliente idcliente="CL2002">
      <nombre>Nombreclientesuno</nombre>
      <apellido1>Apellidouno</apellido1>
      <apellido2>Apellidodos</apellido2>
      <telefonoContacto>222222222</telefonoContacto>
      <correo>correo@clientes2.com</correo>
      <fechaNacimiento>2023/11/1</fechaNacimiento>
      <alquilerActivos>
        <alquiler idvehiculo="Ca2000">
          <inicio>2023/11/1</inicio>
          <fin>2023/11/1</fin>
        </alquiler>
      </alquilerActivos>
      <alquilerTerminados>
        <alquiler idvehiculo="Ca2000">
          <inicio>2023/11/1</inicio>
          <fin>2023/11/1</fin>
        </alquiler>
      </alquilerTerminados>
    </cliente>
  </clientes>

</gestionAlquiler>
