=== MateoCarballo/LenguajeDeMarcas/Examenes/Examen LXM Primer Trimestre/reservas_enu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Documento: reservas_enu.xsd-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="reservas">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="reserva"/>
        <xs:element ref="cliente"/>
      </xs:choice>
    </xs:complexType>
    
  </xs:element>
  <xs:element name="reserva">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fecha"/>
        <xs:element name="evento" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="cliente" type="xs:string" use="required"/>
      <xs:attribute name="local" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="cliente">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="dni" type="xs:string"/>
        <xs:element name="nombreCliente" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="codCliente" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
<xs:element name="fecha">
<xs:complexType>
<xs:attribute name="mes" type="xs:string"/>
<xs:attribute name="dia" type="xs:string"/>
<xs:attribute name="horario" type="xs:string"/>
</xs:complexType>
</xs:element>
  
  

</xs:schema>

=== MateoCarballo/LenguajeDeMarcas/Evaluacion_01/Examenes/Examen LXM Primer Trimestre/reservas_enu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Documento: reservas_enu.xml-->
<reservas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xsi:noNamespaceSchemaLocation="reservas_enu.xsd">
   <reserva cliente="P-324" local="localSocial">
    <fecha mes="10" dia="15" horario="tarde"/>
    <evento>Cumpleaños</evento>
  </reserva>
  <reserva cliente="E-107" local="polideportivo">
    <fecha mes="10" dia="15" horario="dia"/>
    <evento>Torneo pádel</evento>
  </reserva>
  <cliente codCliente="P-324">
    <dni>25652358-Z-P</dni>
    <nombreCliente>Juan Torres Pardo</nombreCliente>
  </cliente>
  <cliente codCliente="E-107">
    <dni>45789545-P</dni>
    <nombreCliente>Jacinto Zarra Viñas</nombreCliente>
  </cliente>
  <cliente codCliente="S-86">
    <dni>47878452-A</dni>
    <nombreCliente>Isabel Parra</nombreCliente>
  </cliente>
</reservas>
