=== MateoCarballo/LenguajeDeMarcas/Evaluacion_01/Examenes/Examen LXM Primer Trimestre/reservas_res.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Documento: resolucion reservas_enu Mateo-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- DEFINICION DE LOS ELEMENTOS-->
  <xs:element name="reservas">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="reserva"/>
        <xs:element ref="cliente"/>
      </xs:choice>
    </xs:complexType>
    <xs:key name="codigoCliente">
        <xs:selector xpath="cliente" />
        <xs:field xpath="@codCliente" />
    </xs:key>
    <xs:keyref name="claveReferenciada" refer="codigoCliente">
        <xs:selector xpath="reserva" />
        <xs:field xpath="@cliente" />
    </xs:keyref> 
  </xs:element>
  
        <xs:element name="reserva">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="local" type="tipoLocal"/>
              <xs:element ref="fecha"/>
              <xs:element name="evento" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="cliente" type="tipoCliente" use="required"/>
          </xs:complexType>
        </xs:element>

                  <xs:element name="fecha">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="mes" type="xs:string"/>
                        <xs:element name="dia" type="xs:string"/>
                        <xs:element name="horario" type="tipoHorario"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>  
  
        <xs:element name="cliente">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="dni" type="tipoDNI"/>
              <xs:element ref="nombreCliente"/>
              <xs:element name="tasaDescuento" type="tipoTasa"/>
            </xs:sequence>
            <xs:attribute name="codCliente" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
  
               <xs:element name="nombreCliente">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombre" type="xs:string"/>
                    <xs:element name="apellido1" type="xs:string"/>
                    <xs:element name="apellido2" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element> 
  
  
  <!--TIPOS DE DATOS DECLARADOS-->
  <xs:simpleType name="tipoDNI">
  <xs:restriction base="xs:string">
    <xs:pattern value="[0-9]{8}-[A-Za-z]{1}"/>
  </xs:restriction>
</xs:simpleType>
  
  <xs:simpleType name="tipoTasa">
  <xs:restriction base="xs:decimal">
    <xs:fractionDigits value="2"/>
  </xs:restriction>
</xs:simpleType>
  
<xs:simpleType name="tipoCliente">
  <xs:restriction base="xs:string">
    <xs:pattern value="[PES]{1}-[0-9]{2,3}"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="tipoLocal">
  <xs:restriction base="xs:string">
    <xs:enumeration value="polideportivo"/>
    <xs:enumeration value="localSocial"/>
    <xs:enumeration value="auditorio"/>
  </xs:restriction>
</xs:simpleType> 

<xs:simpleType name="tipoHorario">
  <xs:restriction base="xs:string">
    <xs:enumeration value="maña"/>
    <xs:enumeration value="tarde"/>
    <xs:enumeration value="dia"/>
  </xs:restriction>
</xs:simpleType>

</xs:schema>

=== MateoCarballo/LenguajeDeMarcas/Examenes/Examen LXM Primer Trimestre/reservas_v4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Documento: reservas_v4.xml-->
<reservas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                  xsi:noNamespaceSchemaLocation="reservas_res.xsd">

  <reserva cliente="P-324">
    <local>localSocial</local>
    <fecha>
      <mes>10</mes>
      <dia>15</dia>
      <horario>tarde</horario>
    </fecha>
    <evento>Cumpleaños</evento>
  </reserva>
  
  <reserva cliente="E-107">
    <local>polideportivo</local>
    <fecha>
      <mes>10</mes>
      <dia>15</dia>
      <horario>dia</horario>
    </fecha>
    <evento>Torneo pádel</evento>
  </reserva>
  
  <cliente codCliente="P-324">
    <dni>25652358-Z</dni>
    <nombreCliente>
      <nombre>Juan</nombre>
      <apellido1>Torres</apellido1>
      <apellido2>Pardo</apellido2>
    </nombreCliente>
    <tasaDescuento>0.25</tasaDescuento>
  </cliente>
  
  <cliente codCliente="E-107">
    <dni>45789545-P</dni>
    <nombreCliente>
      <nombre>Jacinto</nombre>
      <apellido1>Zarra</apellido1>
      <apellido2>Viñas</apellido2>
    </nombreCliente>
    <tasaDescuento>0.15</tasaDescuento>
  </cliente>
  
  <cliente codCliente="S-86">
    <dni>47878452-a</dni>
    <nombreCliente>
    <nombre>Isabel</nombre>
    <apellido1>Parra</apellido1>
    <apellido2>Parra</apellido2>
    </nombreCliente>
    <tasaDescuento>0.30</tasaDescuento>
  </cliente>
  
  <!-- Lo creo para comprobar que si añado un cliente no tiene porque aparecer referenciado en las reservas-->
  <cliente codCliente="S-861">
    <dni>47878452-a</dni>
    <nombreCliente>
    <nombre>Isabel</nombre>
    <apellido1>Parra</apellido1>
    </nombreCliente>
    <tasaDescuento>0.30</tasaDescuento>
  </cliente>
</reservas>
