=== MateoCarballo/LenguajeDeMarcas/PRACTICAS XML CLASE/EJERCICIOS PLATEGA DTD/Tarefa_5_B.dtd
<!ELEMENT reservas (reserva+)>
<!ATTLIST reservas
<!ELEMENT reserva (data, informacion,(clienteEmpresa|clientePersonal))>
<!ATTLIST reserva
ano CDATA #REQUIRED>
<!ELEMENT data (#PCDATA)>
<!ELEMENT informacion (#PCDATA)>
<!ELEMENT clienteEmpresa (#PCDATA)>
<!ELEMENT clientePersonal (#PCDATA)>
<!ATTLIST data 
mes CDATA #REQUIRED
dia CDATA #REQUIRED
horario (maÃ±a|tarde|dia) "tarde"
>


local (Polideportivo|Local) #REQUIRED
bonificacion CDATA #IMPLIED>

=== MateoCarballo/LenguajeDeMarcas/PRACTICAS XML CLASE/EJERCICIOS PLATEGA DTD/Tarefa_5_B_conDTD.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE reservas SYSTEM "Tarefa_5_B.dtd"[]>

<reservas ano="2023">

      <reserva local ="Polideportivo" bonificacion="0">
            <data mes="Enero" dia="11" horario="maña"></data>
            <informacion>Informacion del evento</informacion>
            <clienteEmpresa>Informacion Cliente Empresa</clienteEmpresa>
      </reserva>
      
      <reserva local ="Local" bonificacion="1">
            <data mes="Febrero" dia="22"></data>
            <informacion>Informacion del evento</informacion>
            <clientePersonal>Informacion Cliente Personal</clientePersonal>
      </reserva>
      
</reservas>
