=== MateoCarballo/LenguajeDeMarcas/Ejercicios/DTD/Carpeta Personal/PRACTICAS XML CLASE/EJERCICIOS PLATEGA DTD/Ejercicios 6/Tarefa_6_C.dtd
<!ELEMENT material (libro?,artigo?)>
<!ELEMENT libro (titulo,editorial,autor,ano)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT editorial (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT ano (#PCDATA)>
<!ATTLIST libro ISBN CDATA #REQUIRED>

<!ELEMENT artigo (titulo,revista)>
      <!ELEMENT revista (nome,paxina)>
          <!ELEMENT nome (#PCDATA)>
          <!ELEMENT paxina (#PCDATA)>
<!ATTLIST revista numero CDATA #REQUIRED>

=== MateoCarballo/LenguajeDeMarcas/PRACTICAS XML CLASE/EJERCICIOS PLATEGA DTD/Ejercicios 6/Tarefa_6_C.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE material SYSTEM "Tarefa_6_C.dtd" >

<material>

 <libro ISBN="X9-8998">
       <titulo>Inverno na Pereira</titulo>
       <editorial>Toxo verde</editorial>
       <autor>Xurxo Cancelas Brión</autor>
       <ano>2008</ano>
 </libro> 
 
 <artigo>
       <titulo>O carballo</titulo>
       <revista numero="32">
           <nome>Natureza Verde</nome>
           <paxina>4</paxina>
       </revista>
 </artigo> 
 
</material>
