<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reservas[ 
 <!ELEMENT reservas (reserva+,cliente+)>
 <!ELEMENT reserva (data_inicio, data_fin)>
 <!ELEMENT data_inicio (observacións*)>
 <!ELEMENT data_fin (observacións*)>
 <!ELEMENT observacións (#PCDATA)>
 <!ELEMENT cliente (nome, apelidos, mobil, correo*)>
 <!ELEMENT nome (#PCDATA)>
 <!ELEMENT apelidos (#PCDATA)>
 <!ELEMENT mobil (#PCDATA)>
 <!ELEMENT correo (#PCDATA)>
 <!ATTLIST reserva 
cliente CDATA #REQUIRED
tipo (SA|AD|MP|PC|TI) #REQUIRED>

<!ATTLIST data_inicio
ano CDATA #REQUIRED
mes (Enero | febreiro | Marzo | Abril | Mayo | Junio | Julio | Agosto | Septiembre | Octubre | Noviembre | Diciembre) #REQUIRED
día CDATA #REQUIRED>

 <!ATTLIST data_fin
ano CDATA #REQUIRED
mes (Enero | febreiro | Marzo | Abril | Mayo | Junio | Julio | Agosto | Septiembre | Octubre | Noviembre | Diciembre) #REQUIRED
día CDATA #REQUIRED>

<!ATTLIST cliente id CDATA #REQUIRED>

 ]>

<reservas>
<reserva cliente="CLI1" tipo="AD">
<data_inicio ano="2013" mes="febreiro" día="5">
<observacións>Chegan sobre as 23:30</observacións>
</data_inicio>
<data_fin ano="2013" mes="febreiro" día="9" />
</reserva>
<reserva cliente="CLI2" tipo="MP">
<data_inicio ano="2013" mes="febreiro" día="7" />
<data_fin ano="2013" mes="febreiro" día="15">
<observacións>Saída as 16:00</observacións>
</data_fin>
</reserva>
<!-- El tipo TI que aparece aqui no se especifica en el enunciado. Lo añado a las posibilidades para este atributo-->
<reserva cliente="CLI1" tipo="TI">
<data_inicio ano="2013" mes="febreiro" día="18" />
<data_fin ano="2013" mes="febreiro" día="23" />
</reserva>
<cliente id="CLI1">
<nome>Eva</nome>
<apelidos>Sobral García</apelidos>
<mobil>688998899</mobil>
<correo>eva.sobral@meucorreo.com</correo>
</cliente>
<cliente id="CLI2">
<nome>Xan</nome>
<apelidos>López Paz</apelidos>
<mobil>677778899</mobil>
</cliente>
</reservas>
<!-- 

a)Tarefa6a
Dado o seguinte documento XML, deseña un DTD que o valide tendo en conta que:
 Todos os atributos son requeridos.
– O atributo habitación pode tomar os valores: Dobre ou Individual.
– O atributo tipo pode tomar os valores: SA, AD, MP ou PC.
– O atributo mes unicamente pode tomar como valor os nomes dos meses do ano.
 Debes empregar entidades onde che pareza convinte.
XML
<?xml version="1.0" encoding="UTF-8"?>
<reservas>
<reserva cliente="CLI1" tipo="AD">
<data_inicio ano="2013" mes="febreiro" día="5">
<observacións>Chegan sobre as 23:30</observacións>
</data_inicio>
<data_fin ano="2013" mes="febreiro" día="9" />
</reserva>
<reserva cliente="CLI2" tipo="MP">
<data_inicio ano="2013" mes="febreiro" día="7" />
<data_fin ano="2013" mes="febreiro" día="15">
<observacións>Saída as 16:00</observacións>
</data_fin>
</reserva>
<reserva cliente="CLI1" tipo="TI">
<data_inicio ano="2013" mes="febreiro" día="18" />
<data_fin ano="2013" mes="febreiro" día="23" />
</reserva>
<cliente id="CLI1">
<nome>Eva</nome>
<apelidos>Sobral García</apelidos>
<mobil>688998899</mobil>
<correo>eva.sobral@meucorreo.com</correo>
</cliente>
<cliente id="CLI2">
<nome>Xan</nome>
<apelidos>López Paz</apelidos>
<mobil>677778899</mobil>
</cliente>
</reserva>

 -->
