=== MateoCarballo/LenguajeDeMarcas/Ejercicios/XSD/Carpeta Personal/Tarefa_02_A_PLATEGA/Tarefa_02_B.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Documento para validar Tarefa_02_B.xml de platega Esquemas
La norma que intento seguir es que los tipos de datos complejos
 los nombro com "type" mas el nombre que tendrá el elemento
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!--Declaracion del elemento "UD" -->
<xs:complexType name="UD">
  <xs:sequence>
  <!-- Si no especificamos nada por defecto son opcionales-->
  <xs:element name="Titulo" type="xs:string" use="required"/>
  <xs:element name="Descripcion" type="xs:string" use="optional"/>
  </xs:sequence>
  <xs:attribute name="Numero" type="xs:integer" use="required"/>
  <xs:attribute name="Sesions" type="xs:integer" use="required"/>
  </xs:complexType>

<!-- Declaracion del elemento "Contidos"-->
 <xs:complexType name="typeContidos">
  <xs:sequence>
  <!-- unbounded indica que el numero maximo es ilimitado y al no tener minimo el minimo=1 -->
  <xs:element name="UnidadeDidactica" type="UD" maxOccurs="unbounded"/>
  </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="typeCiclo">
  <xs:sequence>
  <xs:element name="Ciclo" type="xs:string" maxOccurs="5"/>
  </xs:sequence>
  </xs:complexType>
  
   <xs:complexType name="typeDuracion">
  <xs:attribute name="duracion" type="xs:integer" use="required"/>
  <xs:attribute name="sesionsSemanais" type="xs:integer" use="required"/>
  <xs:attribute name="sesionsAnuais" type="xs:integer" />
  </xs:complexType>
  
  <xs:element name="Modulo">
    <xs:complexType>
      <xs:sequence>
      <xs:element name="Duracion" type="typeDuracion"/>
      <xs:element name="Nome" type="xs:string"/>
      <xs:element name="Ciclos" type="typeCiclo"/>
      <xs:element name="Contidos" type="typeContidos"/>
      </xs:sequence>
      <xs:attribute name="codigo" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
 
</xs:schema>

=== MateoCarballo/LenguajeDeMarcas/Ejercicios/XSD/Carpeta Personal/Tarefa_02_A_PLATEGA/Tarefa_02_B.xml
<?xml version="1.0" encoding="UTF-8"?> 
<Modulo xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
                xs:noNamespaceSchemaLocation="Tarefa_02_B.xsd"
                codigo="LM-DAM">

  <Duracion duracion="150" sesionsSemanais="3" sesionsAnuais="120"/>

  <Nome>Lenguaje de Marcas</Nome>


<Ciclo>Superior de DAM</Ciclo>
<Ciclo>Superior de DAM</Ciclo>
<Ciclo>Superior de DAM</Ciclo>

  <Contidos>
    <UnidadeDidactica Numero="1" Sesions="40">
      <Titulo>Introducción a XML</Titulo>
      <Descripcion>Conceptos básicos de XML y su estructura.</Descripcion>
    </UnidadeDidactica>

    <UnidadeDidactica Numero="2" Sesions="50">
      <Titulo>Validación y Transformación con XSD y XSLT</Titulo>
      <Descripcion>Uso de XSD para validar documentos XML y XSLT para transformación.</Descripcion>
    </UnidadeDidactica>

    <UnidadeDidactica Numero="3" Sesions="30">
      <Titulo>Desarrollo de documentos XML</Titulo>
      <Descripcion>Creación y manipulación de documentos XML.</Descripcion>
    </UnidadeDidactica>
  </Contidos>

</Modulo>
