=== MateoCarballo/LenguajeDeMarcas/Ejercicios/XSD/Carpeta Personal/Platega/Tarefa_02/Tarefa_02_B_Con_Referencias.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Documento para validar Tarefa_02_B.xml de platega Esquemas
 
<Ciclo xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="Tarefa_02_B.xsd"> 
 
<xs:element name="">
    <xs:complexType>
      <xs:sequence>
      </xs:sequence>
      <xs:attribute name="" type="xs:" use="required"/>
    </xs:complexType>
  </xs:element> 
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Modulo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Duracion"/>
        <xs:element name="Nome" type="xs:string"/>
        <xs:element ref="Ciclos"/>
        <xs:element ref="Contidos"/>
      </xs:sequence>
      <xs:attribute name="codigo" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
   <xs:element name="Duracion">
    <xs:complexType>
      <xs:sequence>
      </xs:sequence>
      <xs:attribute name="horas" type="xs:short" use="required"/>
      <xs:attribute name="sesionsSemanais" type="xs:short" use="required"/>
      <xs:attribute name="sesionsAnuais" type="xs:short" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Ciclos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Ciclo" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Ciclo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="codigo" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Contidos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="UnidadeDidactica" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element> 
  
  <xs:element name="UnidadeDidactica">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Titulo" type="xs:string"  minOccurs="0" maxOccurs="1"  />
        <xs:element name="Descripcion" type="xs:string" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="numero" type="xs:short" use="required"/>
      <xs:attribute name="sesions" type="xs:short" use="required"/>
    </xs:complexType>
  </xs:element>
  
 
</xs:schema>

=== MateoCarballo/LenguajeDeMarcas/Evaluacion_01/Ejercicios/XSD/Carpeta Personal/Platega/Tarefa_02/Tarefa_02_B.xml
<?xml version="1.0" encoding="UTF-8"?> 
<Modulo xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
                xs:noNamespaceSchemaLocation="Tarefa_02_B_Con_Referencias.xsd"
                codigo="MP0373">

<Duracion horas="150" sesionsSemanais="3" sesionsAnuais="120"/>
<Nome>Linguaxes de marcas e sistemas de xestión da información</Nome>
<Ciclo codigo="CSIFC01">Administración de sistemas informáticos e redes</Ciclo>
<Ciclo codigo="CSIFC02">Desenvolvemento de aplicacións multiplataforma</Ciclo>
<Ciclo codigo="CSIFC03">Desenvolvemento de aplicacións web</Ciclo>
<Contidos>
  <UnidadeDidactica numero="1" sesions="40">
      <Titulo>Aplicacións web. Introdución aos linguaxes de marcas</Titulo>
      <Descripcion>Introdución aos conceptos relacionados coas aplicacións web.
      Páxinas web estáticas e dinámicas. Introdución aos linguaxes
      de marcas.
      </Descripcion>
    </UnidadeDidactica>
    <UnidadeDidactica numero="2" sesions="50">
      <Titulo>Linguaxes de marcas para a transmisión de información a través da Web: HTML.</Titulo>
    </UnidadeDidactica>
    <UnidadeDidactica numero="3" sesions="30">
      <Titulo>Linguaxes de marcas para a transmisión de información a través da Web: CSS</Titulo>
      <Descripcion>Separar o contido da presentación. Follas de estilo CSS.</Descripcion>
    </UnidadeDidactica>
</Contidos>
</Modulo>
