=== MateoCarballo/LenguajeDeMarcas/Ejercicios/XSD/Carpeta Personal/Platega/Tarefa_03/Tarefa_03.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- Lo que teniamos en el ejercicio 1 de platega era así
<xs:complexType name="tipoNeno">
    <xs:sequence>
      <xs:element name="nome" type="xs:string"/>
      <xs:element name="dataNacemento" type="xs:date"/>
      <xs:element name="peso" type="xs:decimal"/>
      <xs:element name="altura" type="xs:unsignedByte"/>
      <xs:element name="vacunas" type="xs:boolean"/>
    </xs:sequence>
  <xs:attribute name="numeroExpedente" type="xs:unsignedShort"/>
  </xs:complexType>
-->

<!-- ENUNCIADO 
a) Tarefa 3_a
Modificar o documento xml e o esquema XML correspondente a gardería para:
▪ engadir ao neno un elemento sexo obrigatorio que pode tomar os valores H ou M. 
▪ o elemento peso debe ter sempre un decimal.
▪ o tamaño mínimo do nome será de 3 caracteres e o máximo de 80.
▪ engadir ao neno un atributo codigo que terá o seguinte formato:
– o primeiro caracter será unha P ou unha M
– a continuación irán dous número entre o 3 e o 7
– a continuación pode levar un - e tres díxitos máis.
– Posibles exemplos deste serían: P44, P44-323, P65-100
▪ engadir ao neno os teléfonos de contacto. Para elo crearase un elemento contacto por
cada teléfono que teñamos do neno. O elemento debe ter:
– un atributo relación para indicar o parentesco co neno, que só poderá tomar os
seguintes valores: nai, pai, avó/a, titor, outra.
– o teléfono debe permitir introducir unicamente 9 números.
– como moito gardaremos 4 contactos por cada neno.
▪ incluir un elemento idade baleiro en neno con dous atributos:
– un atributo anos que pode tomar valores entre 0 e 3
– un atributo meses que pode tomar valores entre 0 e 11
  
<xs:element name="">
      <xs:simpleType>
          <xs:restriction base="">
          </xs:restriction>
      </xs:simpleType>
</xs:element> 
-->
<xs:element name="garderia">
  <xs:complexType>
    <xs:sequence>
    <xs:element ref="neno" minOccurs="1" maxOccurs="50"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="neno">
  <xs:complexType>
    <xs:sequence> 
    <xs:element ref="sexo" maxOccurs="50"/>
    <xs:element ref="nome"/>
    <xs:element ref="dataNacemento"/>
    <xs:element ref="peso"/>
    <xs:element name="altura" type="xs:unsignedByte"/>
    <xs:element ref="contactos"/>
    <xs:element ref="idade"/> 
    </xs:sequence>
    <xs:attribute name="numeroExpedente" type="xs:unsignedShort"/>
      <xs:simpleType>
          <xs:restriction base="xs:unsignedShort">
            <xs:patter value="[0-9]{4}"/>
          </xs:restriction>
        </xs:simpleType>
    <xs:attribute name="numeroExpedente" type="xs:unsignedShort"/>
      <xs:simpleType>
            <xs:restriction base="xs:unsignedShort">
              <xs:patter value="[PM][3-7]-([0-9]{3})*"/>
            </xs:restriction>
      </xs:simpleType>
  </xs:complexType>
</xs:element>

<xs:element name="sexo">
      <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:patter value="[HM]"/>
          </xs:restriction>
      </xs:simpleType>
</xs:element>

<xs:element name="nome">
      <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
            <xs:maxLength value="80"/>
          </xs:restriction>
      </xs:simpleType>
</xs:element> 

<xs:element name="dataNacemento">
      <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:patter value="([2000-2023]-[1-11]-[1-31])"/>
          </xs:restriction>
      </xs:simpleType>
</xs:element> 

<xs:element name="peso">
      <xs:simpleType>
          <xs:restriction base="xs:decimal">
            <xs:totalDigits value="3"/>
            <xs:fractionDigits value="1"/>
          </xs:restriction>
      </xs:simpleType>
</xs:element> 

<xs:element name="contactos">
      <xs:complexType>
          <xs:sequence>
          <xs:element ref="contacto" maxOccurs="4"/>
          </xs:sequence>
      </xs:complexType>
</xs:element> 

<xs:element name="contacto">
       <xs:complexType>
          <xs:sequence>
            <xs:element ref="telefono"/>
          </xs:sequence>
          <xs:attribute name="relacion" type="xs:string"/>
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:patter value="[pai][nai][avo][avoa][titor][outra]"/>
              </xs:restriction>
            </xs:simpleType>
      </xs:complexType>
</xs:element> 

<xs:element name="telefono"/>
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:totalDigits value="9"/>
    </xs:restriction>
   </xs:simpleType>
</xs:element> 

<xs:element name="idade">
      <xs:complexType>
          <xs:restriction base="">
          </xs:restriction>
      </xs:complexType>
      <xs:attribute name="anos" type="xs:Short"/>
        <xs:simpleType>
          <xs:restriction base="xs:short">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="3"/>
          </xs:restriction>
        </xs:simpleType>
      <xs:attribute name="meses" type="xs:Short"/>
        <xs:simpleType>
          <xs:restriction base="xs:short">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="11"/>
          </xs:restriction>
        </xs:simpleType>
</xs:element> 

</xs:schema>

=== MateoCarballo/LenguajeDeMarcas/Ejercicios/XSD/Carpeta Personal/Platega/Tarefa_03/Tarefa_03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- tarefa 1 UD7 -->
<garderia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Tarefa_03.xsd">

  <neno numeroExpedente="2344" codigo="P73-123">
    <sexo>M</sexo>
    <nome>Noa Blanco Coello</nome>
    <dataNacemento>2010-10-12</dataNacemento>
    <peso>13.5</peso>
    <altura>78</altura>
    <vacunas>true</vacunas>
    <contactos>
      <contacto relacion="pai">
        <telefono>123456789</telefono>
      </contacto>
    </contactos>
    <idade anos="0" meses="11"/>
  </neno>
</garderia>
