=== MateoCarballo/LenguajeDeMarcas/Entregables/Entregable_0/Entregable.dtd
<!ENTITY % FormatoFecha
"ano CDATA #REQUIRED
  mes (Enero|Febrero|Marzo|Abril|Mayo|Junio|Julio|Agosto|Septiembre|Octubre|Noviembre|Diciembre) #REQUIRED
  dia CDATA #REQUIRED">

<!ELEMENT RedAlquiler (Sucursal+, Clientes)>
<!ATTLIST RedAlquiler
nombre CDATA #REQUIRED
>

<!ELEMENT Sucursal (Vehiculo+)>
<!ATTLIST Sucursal 
cantidadTotalVehiculos CDATA #IMPLIED
direccion CDATA #REQUIRED
>

<!ELEMENT Clientes (Cliente+)>
<!ATTLIST Clientes cantidadTotalClientes CDATA #IMPLIED>

<!ELEMENT Vehiculo (Tipo, Marca, Modelo, FechaMatriculacion, Kilometraje, Matricula, Potencia, Peso,PrecioDia,Descripcion)>
<!ATTLIST Vehiculo idVehiculo ID #REQUIRED>

<!ELEMENT Tipo (#PCDATA)>
<!ELEMENT Marca (#PCDATA)>
<!ELEMENT Modelo (#PCDATA)>
<!ELEMENT FechaMatriculacion EMPTY>
<!ATTLIST FechaMatriculacion
  %FormatoFecha;
>

<!ELEMENT Kilometraje (#PCDATA)>
<!ELEMENT Matricula (#PCDATA)>
<!ELEMENT Potencia (#PCDATA)>
<!ATTLIST Potencia unidades CDATA #REQUIRED>

<!ELEMENT Peso (#PCDATA)>
<!ATTLIST Peso unidades CDATA #REQUIRED>

<!ELEMENT PrecioDia (#PCDATA)>
<!ATTLIST PrecioDia moneda CDATA #REQUIRED>
<!ELEMENT Descripcion (#PCDATA)>

<!ELEMENT Cliente (Nombre, Apellidos, Tfno, Correo, FechaNacimiento, AlquilerRealizado?)>
<!ATTLIST Cliente idCliente ID #REQUIRED>

<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Apellidos (#PCDATA)>
<!ELEMENT Tfno (#PCDATA)>
<!ELEMENT Correo (#PCDATA)>
<!ELEMENT FechaNacimiento EMPTY>
<!ATTLIST FechaNacimiento
  %FormatoFecha;
>
<!ELEMENT AlquilerRealizado (VehiculoAlquilado,Inicio,Fin)>
<!ELEMENT VehiculoAlquilado (#PCDATA)>
<!ELEMENT Inicio EMPTY>
<!ATTLIST   Inicio
%FormatoFecha;>
<!ELEMENT Fin EMPTY>
<!ATTLIST   Fin
%FormatoFecha;>
<!ATTLIST VehiculoAlquilado idVehiculo IDREF #REQUIRED>

=== MateoCarballo/LenguajeDeMarcas/Entregables/Entregable_0/Entregable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RedAlquiler SYSTEM "Entregable.dtd">

<RedAlquiler>
<Vehiculos cantidadTotal="345">

<Vehiculo idVehiculo="Co1000">
<Tipo>Coche</Tipo>
<Marca>MarcaDeCoche</Marca>
<Modelo>ModeloDeCoche</Modelo>
<FechaMatriculacion ano="2023" mes="Enero" dia="1"/>
<Kilometraje>210000</Kilometraje>
<Matricula>1234ABC</Matricula>
<Potencia unidades="cv">100</Potencia>
<Peso unidades="kg">1450</Peso>
</Vehiculo>

<Vehiculo idVehiculo="Fu2000">
<Tipo>Furgoneta</Tipo>
<Marca>MarcaDeFurgoneta</Marca>
<Modelo>ModeloDeFurgoneta</Modelo>
<FechaMatriculacion ano="2023" mes="Enero" dia="1"/>
<Kilometraje>400000</Kilometraje>
<Matricula>5678DEF</Matricula>
<Potencia unidades="cv">150</Potencia>
<Peso unidades="kg">1750</Peso>
</Vehiculo>

<Vehiculo idVehiculo="Ca3000">
<Tipo>Caravana</Tipo>
<Marca>MarcaDeCaravana</Marca>
<Modelo>ModeloDeCaravana</Modelo>
<FechaMatriculacion ano="2023" mes="Enero" dia="1"/>
<Kilometraje>50000</Kilometraje>
<Matricula>9012GHI</Matricula>
<Potencia unidades="cv">200</Potencia>
<Peso unidades="kg">3500</Peso>
</Vehiculo>

</Vehiculos>

<Clientes cantidadTotal="543">
<Cliente idCliente="CL0001">
<Nombre>nombrecliente1</Nombre>
<Apellidos>Apellido1 Apellido2</Apellidos>
<Tfno>111111111</Tfno>
<Correo>correo@cliente1.com</Correo>
<FechaNacimiento ano="1993" mes="Enero" dia="1"/>
<VehiculoAlquilado idVehiculo="Ca3000"/>
</Cliente>

<Cliente idCliente="CL0002">
<Nombre>nombrecliente2</Nombre>
<Apellidos>Apellido1 Apellido2</Apellidos>
<Tfno>222222222</Tfno>
<Correo>correo@cliente2.com</Correo>
<FechaNacimiento ano="1993" mes="Enero" dia="1"/>
<VehiculoAlquilado idVehiculo="Co1000"/>
</Cliente>

</Clientes>

</RedAlquiler>
